package homebrew

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const repo = "https://github.com/statikowsky/mar"

var requiredArchives = []string{
	"mar_darwin_arm64.tar.gz",
	"mar_darwin_amd64.tar.gz",
	"mar_linux_arm64.tar.gz",
	"mar_linux_amd64.tar.gz",
}

type formulaData struct {
	Tag         string
	Version     string
	DarwinARM64 string
	DarwinAMD64 string
	LinuxARM64  string
	LinuxAMD64  string
}

// RenderFormula renders the Homebrew formula for a release tag using the
// release checksums.txt generated by make release.
func RenderFormula(tag string, checksums io.Reader) (string, error) {
	tag = strings.TrimSpace(tag)
	if tag == "" {
		return "", fmt.Errorf("tag is required")
	}
	sums, err := parseChecksums(checksums)
	if err != nil {
		return "", err
	}
	for _, archive := range requiredArchives {
		if sums[archive] == "" {
			return "", fmt.Errorf("checksum for %s not found", archive)
		}
	}

	data := formulaData{
		Tag:         tag,
		Version:     strings.TrimPrefix(tag, "v"),
		DarwinARM64: sums["mar_darwin_arm64.tar.gz"],
		DarwinAMD64: sums["mar_darwin_amd64.tar.gz"],
		LinuxARM64:  sums["mar_linux_arm64.tar.gz"],
		LinuxAMD64:  sums["mar_linux_amd64.tar.gz"],
	}

	var out bytes.Buffer
	if err := formulaTemplate.Execute(&out, data); err != nil {
		return "", fmt.Errorf("render formula: %w", err)
	}
	return out.String(), nil
}

// WriteFormula writes a rendered formula, creating the Formula directory if
// the tap checkout is empty.
func WriteFormula(path, formula string) error {
	if strings.TrimSpace(path) == "" {
		return fmt.Errorf("formula path is required")
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create formula dir: %w", err)
	}
	if err := os.WriteFile(path, []byte(formula), 0o644); err != nil {
		return fmt.Errorf("write formula: %w", err)
	}
	return nil
}

func parseChecksums(r io.Reader) (map[string]string, error) {
	sums := make(map[string]string)
	sc := bufio.NewScanner(r)
	for sc.Scan() {
		fields := strings.Fields(sc.Text())
		if len(fields) < 2 {
			continue
		}
		archive := strings.TrimPrefix(fields[1], "*")
		sums[archive] = fields[0]
	}
	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("read checksums: %w", err)
	}
	return sums, nil
}

var formulaTemplate = template.Must(template.New("formula").Parse(`class Mar < Formula
  desc "Local-first project memory: Markdown docs + kanban tasks"
  homepage "` + repo + `"
  version "{{.Version}}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "` + repo + `/releases/download/{{.Tag}}/mar_darwin_arm64.tar.gz"
      sha256 "{{.DarwinARM64}}"
    else
      url "` + repo + `/releases/download/{{.Tag}}/mar_darwin_amd64.tar.gz"
      sha256 "{{.DarwinAMD64}}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "` + repo + `/releases/download/{{.Tag}}/mar_linux_arm64.tar.gz"
      sha256 "{{.LinuxARM64}}"
    else
      url "` + repo + `/releases/download/{{.Tag}}/mar_linux_amd64.tar.gz"
      sha256 "{{.LinuxAMD64}}"
    end
  end

  def install
    bin.install "mar"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mar version")
  end
end
`))
